import { Roboto_Mono, Smooch_Sans } from "next/font/google";
import React from "react";

import { cn } from "@/shared/lib/utils";
import { Header } from "@/widgets/header";

import type { Metadata } from "next";

import "./globals.css";

//дефолтный шрифт
const roboto = Roboto_Mono({ subsets: ["latin"] });
//для эксперимента второй шрифт через определение переменной окружения
const testFonts = Smooch_Sans({
  variable: "--test-fonts",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, testFonts.variable, "antialiased")}>
        <Header variant="public" />
        {children}
      </body>
    </html>
  );
}
